export enum ConfigName {
  NODE_ENV = 'NODE_ENV',
  NEST_LOG_PATH = 'NEST_LOG_PATH',
  PUBLIC_NEST_SERVER_PORT = 'PUBLIC_NEST_SERVER_PORT',
  PUBLIC_HTTP_HOST = 'PUBLIC_HTTP_HOST',
  PUBLIC_HTTP_SCHEME = 'PUBLIC_HTTP_SCHEME',
  DISABLE_CONSOLE_LOGGER = 'DISABLE_CONSOLE_LOGGER',
  LOCAL_NEST_SERVER_PORT = 'LOCAL_NEST_SERVER_PORT',
}
